[package]
name = "foodterest"
version = "0.1.0"
authors = ["Naylepsh <naylepsh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1.0"
actix-web = "2.0.0"
actix-rt = "1.0.0"